// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lS03z0ml3W9UCJ8nVfb_2BlGWTQXeMU',
    appId: '1:84525309006:web:82f106be559249de1c771f',
    messagingSenderId: '84525309006',
    projectId: 'chatting-app-48b31',
    authDomain: 'chatting-app-48b31.firebaseapp.com',
    storageBucket: 'chatting-app-48b31.appspot.com',
    measurementId: 'G-EP17PXS1DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0yreZMf6dHoOSfOdBKXS_4F2Do6p6R4',
    appId: '1:84525309006:android:670479674addc4231c771f',
    messagingSenderId: '84525309006',
    projectId: 'chatting-app-48b31',
    storageBucket: 'chatting-app-48b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX9hJxg7OFCSQNLYrYMm3DRWSZW2KcIjI',
    appId: '1:84525309006:ios:618c78629af0324d1c771f',
    messagingSenderId: '84525309006',
    projectId: 'chatting-app-48b31',
    storageBucket: 'chatting-app-48b31.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX9hJxg7OFCSQNLYrYMm3DRWSZW2KcIjI',
    appId: '1:84525309006:ios:618c78629af0324d1c771f',
    messagingSenderId: '84525309006',
    projectId: 'chatting-app-48b31',
    storageBucket: 'chatting-app-48b31.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1lS03z0ml3W9UCJ8nVfb_2BlGWTQXeMU',
    appId: '1:84525309006:web:d836decfbfc2d0611c771f',
    messagingSenderId: '84525309006',
    projectId: 'chatting-app-48b31',
    authDomain: 'chatting-app-48b31.firebaseapp.com',
    storageBucket: 'chatting-app-48b31.appspot.com',
    measurementId: 'G-MDWQ7K9DGX',
  );
}
